spring.application.name=oops
server.port=8083

spring.r2dbc.url=r2dbc:mysql://localhost:3306/moviebooking_db
spring.r2dbc.username=root
spring.r2dbc.password=Texas@123

# spring.r2dbc.driver-class-name=com.mysql.cj.jdbc.Driver

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# payments:
razorpay.key.id=rzp_test_T6iTN7bi9XJRsT
razorpay.key.secret=MmlzLzf45x0XjYWi3h1wJyXo
razorpay.currency=INR

logging:
level:
com.yourpackage: DEBUG