spring.application.name=producer

spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

app.rabbitmq.exchange=order.exchange
app.rabbitmq.queue= order.notification
app.rabbitmq.routingkey=order.notification.created


spring.rabbitmq.host=localhost
spring.rabbitmq.virtual-host=/
spring.rabbitmq.connection-timeout=10s

#app.order.routingkey


#app.order.queue
